### ISSUE TITLE
--install options do not have any effect on post hooks

### ISSUE THREAD

**Issue by jk-1** [danny0838/git-store-meta#15]
This is git-store-meta 1.2.6

I tried following:

Clean the dir

	jk@tiira:~/tmp/gittest5$ rm -rf *
	jk@tiira:~/tmp/gittest5$ rm -rf .*
	rm: refusing to remove '.' or '..' directory: skipping '.'
	rm: refusing to remove '.' or '..' directory: skipping '..'

Init git and install git-store-meta without any parameters

	jk@tiira:~/tmp/gittest5$ git init
	Initialized empty Git repository in /home/jk/tmp/gittest5/.git/
	jk@tiira:~/tmp/gittest5$ cp -a /home/jk/workspace/gitsrc/git-store-meta.pl .git/hooks/
	jk@tiira:~/tmp/gittest5$ .git/hooks/git-store-meta.pl --install 
	installing hooks...
	git directory: `.git'
	created `.git/hooks/pre-commit'
	created `.git/hooks/post-checkout'
	created `.git/hooks/post-merge'

Show the post-merge hook

	jk@tiira:~/tmp/gittest5$ cat .git/hooks/post-merge 
	#!/bin/sh
	# when running the hook, cwd is the top level of working tree
	
	is_squash=$1
	
	# apply metadata after a successful non-squash merge
	if [ $is_squash -eq 0 ]; then
	    $(dirname "$0")/git-store-meta.pl --apply -d
	fi
	

So the apply command uses "dir" option although it was NOT given in install command like --install -d

Clean the dir

	jk@tiira:~/tmp/gittest5$ rm -rf *
	jk@tiira:~/tmp/gittest5$ rm -rf .*
	rm: refusing to remove '.' or '..' directory: skipping '.'
	rm: refusing to remove '.' or '..' directory: skipping '..'

Then try to install with mode, access and modification time

	jk@tiira:~/tmp/gittest5$ git init
	Initialized empty Git repository in /home/jk/tmp/gittest5/.git/
	jk@tiira:~/tmp/gittest5$ cp -a /home/jk/workspace/gitsrc/git-store-meta.pl .git/hooks/
	jk@tiira:~/tmp/gittest5$ .git/hooks/git-store-meta.pl --install -f mode,mtime,atime
	installing hooks...
	git directory: `.git'
	created `.git/hooks/pre-commit'
	created `.git/hooks/post-checkout'
	created `.git/hooks/post-merge'

Show the post-merge hook

	jk@tiira:~/tmp/gittest5$ cat .git/hooks/post-merge 
	#!/bin/sh
	# when running the hook, cwd is the top level of working tree
	
	is_squash=$1
	
	# apply metadata after a successful non-squash merge
	if [ $is_squash -eq 0 ]; then
	    $(dirname "$0")/git-store-meta.pl --apply -d
	fi
	jk@tiira:~/tmp/gittest5$ 

So the apply command uses "dir" option although it was NOT given and mode, access and modification time options are not used although they were given.

**Issue 1:** Is it possible to modify the git-store-meta.pl so that it accepts also -f user,group,mode,mtime,atime options and not to use -d option if not given?

**Issue 2:** It seems that if I have an empty (=just initialized) local git repo with git-store-meta.pl installed and then in the local repo I do 

	git pull remote-repo branch

This will NOT run post-merge hook. Is this normal or should it run the post-merge hook?

Thank you for your support.

**Comment by danny0838** [comment]
You have to run `--store` for the first time to define which fields to store and whether to store directory metadata, and such information are recorded in the generated `.git_store_meta` file. `--apply -d` simply means "apply what has been defined" since it applies the fields recorded in the `.git_store_meta` file if `--fields` option is omitted, and directory metadata is applied if (and only if) it exists (i.e. `-d` has been specified when `--store` was run). You can change the behavior by specifying `-f` or remove `-d` for `--apply`, and you can also modify the generated hooks after running `--install` as needed, but it is not necessary in most common cases as you can redefine what to store by running `--store` with options again—that's why the default parameters default hooks are set so.

post-merge hook is not run after `git pull` if the repository has not been initialized (i.e. no HEAD branch). It's a special case defined by git. You have to either init a branch before pull or run the `--apply` by yourself after pull.
