### ISSUE TITLE
Add '--uninstall' option

### ISSUE THREAD

**Issue by jamesquilty** [danny0838/git-store-meta#16]
Really appreciate git-store-meta!
On occasion, I'd like to remove the hooks installed with `--install` and a simple `--uninstall` option to delete the installed files would be appreciated.

**Comment by danny0838** [comment]
We would not implement this since we can hardly tell whether the hooks are modified by the user and auto-removal of them could lead to permanent data loss. Simply remove `hooks/pre-commit`, `hooks/post-checkout`, `hooks/post-merge` manually if you're sure they are simply installed by git-store-meta.

**Comment by jamesquilty** [comment]
Of course we can tell whether the hooks files have been modified: run a hash on them and compare to the known gsm (git-store-meta) hook hashes. It's going to be complicated in a minor way by there being different versions of the hook files... but it's not such a bad thing for there to be a bit of a cost to modifying those. What do you think?

**Comment by danny0838** [comment]
Unfortunately, to support `--target` for `--install` (as in #20), the generated hook contents can be anything, and it's impossible to determine whether they are changed by the user.

We have added `--install --force` to force install new hooks, which would be useful for updating. As respect of uninstallation, manual operation is still required, though the user can write a script for automation if it's done frequently.
