### ISSUE TITLE
Search for git-store-meta on PATH before installing in local repository

### ISSUE THREAD

**Issue by jamesquilty** [danny0838/git-store-meta#17]
At present, the script installs a copy of itself into the local repository from which it was run. Given git's model is "repositories are cheap, create a new one for everything" this will inevitably lead to many copies of git-store-meta.pl which makes updating labour-intensive.

My solution is to place a symbolic link to `git-store-meta.pl` in a directory which is in my PATH environment variable. The symbolic link is connected to a single clone of git-store-meta (gsm) which makes updating gsm as easy as `git pull`. The hook files need some modification so they look for gsm on the path first, before looking locally, but that was easy enough to accomplish.

So, I have a modified script which works on macOS and should also run on Linux, and I was thinking of submitting a pull request if that would be welcome?

**Comment by danny0838** [comment]
Making an installation wizard is complicated, especially when we have to support all major platforms, so we won't implement it unless we have a complete solution.

It's always wellcome to open a pull request, and it's the philosophy of open-source! There's no guarantee whether the request would get approved or not as we'd have our concerns, but your pull request will help people with similar needs, so feel free to do it.

**Comment by jamesquilty** [comment]
This is my first time creating a pull request on GitHub, so a little advice on how to not make more work for everyone through newbie errors would be appreciated. I've forked the project, but then should I myself make a new branch for my modifications or should I attempt to use the existing `devel` branch? If I need to create my own branch, is there a naming convention or preferred name for the branch?

**Comment by danny0838** [comment]
Git is free. Any workflow is mostly determined by project developers. We currently haven't set up any rule about this and you can just create your request in a way you'd like, and we'll check for it. The branch name is also up to you. However, we'd recommand using a name about the topic or feature instead of `master` or `devel`.

**Comment by ha-ju** [comment]
At the first glance, I also found it very tempting to have the main script `git-store-meta.pl` installed only once in a central place that lies within `PATH`. But this would mean to introduce an additional dependency into every repository that refers to that central instance, with at least the following consequences:

1. The corresponding repositories can not be moved freely any more, as they are bound by that dependency.

2. Worse: If future development on git-store-meta breaks backward compatibility to existing hook scripts or meta-data files, updating the central instance will break the corresponding repositories.

So it is better to keep the repositories self-contained and independent from any central instance of `git-store-meta.pl`.

Apart from that, `git-store-meta.pl` can actually be installed in a central place that also might lie within PATH to be used for installation (`--install`). In this way, maintenance steps like updates are easily done but only affect new repositories keeping existing ones operational and everybody happy.

**Comment by danny0838** [comment]
Maybe we can revise the generated hooks to invoke `git-store-meta.pl` (i.e. in PATH) as a fallback of `.git/hooks/git-store-meta.pl` (and, meanwhile, no more copy `git-store-meta.pl` to `.git/hook/` if it doesn't exist). In this way those who prefer a centralized approach can add directory of a `git-store-meta.pl` to PATH and run `git-store-meta.pl --install` for all repos; otherwise include a copy of `git-store-meta.pl` in `.git/hooks/` and run `--install` for every repo.

This should be pretty backward-compatible, though users need to regenerate hooks by themselves.

**Comment by danny0838** [comment]
Implemented in 1.3.3
