### ISSUE TITLE
Feature request: option to either purge or backup non-existent paths

### ISSUE THREAD

**Issue by priyadarshan** [danny0838/git-store-meta#8]
Right now, when git-store-meta is asked to apply metadata to non-existent items, one gets,

```
$ .git/hooks/git-store-meta.pl --apply
applying metadata from .git_store_meta ...
fields: file, type, mode, mtime, atime; directory: no
warn: `attic/filename.txt' does not exist, skip applying metadata
```

If one is tracking large, long-lived repositories, such warnings may become prominent.

It would be quite useful to have a switch to deal with non-existent items, either

1. allow to purge non-existing paths from `.git_store_meta`
2. allow to store non-existent paths to a backup file, perhaps `.git_store_meta_attic`, from where they could be possibly restored in the future.

The second case would be especially useful in conjunction with #4.

Thank you again for git-store-meta. It is truly a gem.

**Comment by danny0838** [comment]
Files that are no more existed (or no more revisioned by git) are removed from records once `git-store-meta --store` or `--update` is run. You might have to find out why you get an inconsistent status. Did you forget to run it after making some change (such as a `git reset --hard`, which won't trigger a hook)?

To purge non-existing paths from .git_store_meta, simply run a `git-store-meta --store`, and commit the revised .git-store-meta file. You can then simply diff the .git-store-meta file between different commits to check what's changed.  There's probably no need to implement a further complicated mechanism for backup since git already does it nicely for us.

**Comment by priyadarshan** [comment]
Thank you, I was not aware that git-store-meta was removing all metadata if not in the filesystem.
Sorry for the noise. This ticket could be closed as far as it concerns me, at your convenience.
